import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import AutoMinorLocator
from os import chdir

chdir("../apr6")

f1=np.loadtxt("freq_538_VNATrc.001")
f2=np.loadtxt("freq_562_VNATrc.001")
f3=np.loadtxt("freq_590_VNATrc.001")

chdir("../process")

fig, ax = plt.subplots()
plt.minorticks_on()
p1, = plt.plot(f3[:,0],f3[:,2]-np.sum(f3[:,2])/len(f1[:,2]))
p2, = plt.plot(f2[:,0],f2[:,2]-np.sum(f2[:,2])/len(f1[:,2]) +100.)
p3, = plt.plot(f1[:,0],f1[:,2]-np.sum(f1[:,2])/len(f1[:,2])+100.)
plt.xlim(0.0,1.6)
plt.ylim(-30.,30.)
plt.ylabel("Phase shift (deg)")
plt.xlabel("Time (s)")
plt.legend([p1,p2,p3],[  "590 GHz",  "562 GHz", "538 GHz"],loc=3)
plt.title("Motion of cryostat")
ax.xaxis.set_minor_locator(AutoMinorLocator(2))
ax.yaxis.set_minor_locator(AutoMinorLocator(2))
plt.savefig("apr6fig1.pdf")
plt.clf()

fig, ax = plt.subplots()
plt.minorticks_on()
p1, = plt.plot(f3[:,0],f3[:,2]-np.sum(f3[:,2])/len(f1[:,2]))
p2, = plt.plot(f2[:,0],f2[:,2]-np.sum(f2[:,2])/len(f1[:,2]))
p3, = plt.plot(f1[:,0],f1[:,2]-np.sum(f1[:,2])/len(f1[:,2])+100.)
plt.xlim(0.0,1.6)
plt.ylim(-30.,30.)
plt.ylabel("Phase shift (deg)")
plt.xlabel("Time (s)")
plt.legend([p1,p2,p3],[  "590 GHz",  "562 GHz", "538 GHz"],loc=3)
plt.title("Motion of cryostat")
ax.xaxis.set_minor_locator(AutoMinorLocator(2))
ax.yaxis.set_minor_locator(AutoMinorLocator(2))
plt.savefig("apr6fig2.pdf")
plt.clf()

fig, ax = plt.subplots()
plt.minorticks_on()
p1, = plt.plot(f3[:,0],f3[:,2]-np.sum(f3[:,2])/len(f1[:,2]))
p2, = plt.plot(f2[:,0],f2[:,2]-np.sum(f2[:,2])/len(f1[:,2]))
p3, = plt.plot(f1[:,0],f1[:,2]-np.sum(f1[:,2])/len(f1[:,2]))
plt.xlim(0.0,1.6)
plt.ylim(-30.,30.)
plt.ylabel("Phase shift (deg)")
plt.xlabel("Time (s)")
plt.legend([p1,p2,p3],[  "590 GHz",  "562 GHz", "538 GHz"],loc=3)
plt.title("Motion of cryostat")
ax.xaxis.set_minor_locator(AutoMinorLocator(2))
ax.yaxis.set_minor_locator(AutoMinorLocator(2))
plt.savefig("apr6fig3.pdf")
plt.clf()